services:
  - type: web
    name: cifake-engine
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8000
      - key: GEMINI_API_KEY
        sync: false
